openapi: "3.0.1"
info:
  title: "OpenAPI definition"
  version: "v0"
servers:
  - url: "http://localhost:8080"
    description: "Generated server url"
paths:
  /recipes:
    get:
      tags:
        - "recipe-controller"
      operationId: "getAllRecipes_1_1"
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: 0
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: 3
        - name: "direction"
          in: "query"
          required: false
          schema:
            type: "string"
            default: "ASC"
        - name: "name"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Recipe"
    put:
      tags:
        - "recipe-controller"
      operationId: "putRecipe"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
      responses:
        '200':
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Recipe"
    post:
      tags:
        - "recipe-controller"
      operationId: "postRecipe"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Recipe"
      responses:
        '200':
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Recipe"
  /recipes/{id}:
    get:
      tags:
        - "recipe-controller"
      operationId: "getRecipeById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        '200':
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Recipe"
    delete:
      tags:
        - "recipe-controller"
      operationId: "deleteRecipe"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        '200':
          description: "OK"
/recipes/{id}/ingredients:
  get:
    tags:
      - "recipe-controller"
    operationId: "getRecipesIngredients"
    parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
          format: "int32"
    responses:
      '200':
        description: "OK"
        content:
          '*/*':
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/Ingredient"
components:
  schemas:
    Ingredient:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        amount:
          type: "number"
          format: "double"
        unit:
          type: "string"
          enum:
            - "TBSP"
            - "TSP"
            - "ML"
            - "L"
            - "GRAMS"
            - "PIECE"
    Recipe:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        prepTime:
          type: "string"
        description:
          type: "string"
        ingredients:
          type: "array"
          items:
            $ref: "#/components/schemas/Ingredient"
        steps:
          type: "array"
          items:
            $ref: "#/components/schemas/Step"
    Step:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        stepNumber:
          type: "integer"
          format: "int32"
        content:
          type: "string"
